"""
Base layout template for all stability analysis pages.

Each equilibrium type (foyer, nœud, selle, etc.) uses this template to display:
1. Back link to Poincaré diagram
2. Title and pedagogical explanation
3. Eigenvalue display
4. System ODE equation
5. Phase portrait diagram
6. Navigation to related pages

The layout is generated by build_stability_layout() which accepts a page_key
to generate unique element IDs for Dash callbacks.
"""

from __future__ import annotations

from typing import Dict

from dash import Input, Output, callback, dcc, html

from src.app.style.components.layout import (content_wrapper, graph_container,
                                             section_card, back_link, 
                                             side_by_side_container, side_by_side_last,
                                             spacing_section, nav_button, code_display,
                                             app_container)
from src.app.style.palette import PALETTE
from src.app.style.text import TEXT
from src.app.style.typography import TYPOGRAPHY


def _slugify(page_key: str) -> str:
    """
    Very small slugifier: lowercase + replace spaces/underscores with hyphens
    and strip leading/trailing hyphens. Meant to keep IDs simple and stable.
    """
    slug = (page_key or "page").lower().replace("_", "-").replace(" ", "-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-") or "page"


def stability_ids(page_key: str) -> Dict[str, str]:
    """
    Provide normalized IDs for the standard placeholders on a stability page.
    """
    slug = _slugify(page_key)
    return {
        "graph": f"ph-{slug}-graph",
        "system_graph": f"ph-{slug}-system-graph",
        "phase": f"ph-{slug}-phase",
        "explication": f"ph-{slug}-explication",
        "eigenvalue_display": f"ph-{slug}-eigenvalue-display",
        "ode_display": f"ph-{slug}-ode-display",
    }


def build_stability_layout(
    page_key: str,
    layout_pedagogic_fn=None,
    tau: float = 0.0,
    delta: float = 0.0,
) -> html.Div:
    """
    Create a base layout for stability pages (static display).

    - Affiche les valeurs propres calculées
    - Diagramme de phase (dcc.Graph)
    - Explication pédagogique (html.Div)

    Args:
        page_key: Unique identifier for the page
        layout_pedagogic_fn: Function returning pedagogical content
        tau: Trace value for this equilibrium type
        delta: Determinant value for this equilibrium type
    """
    ids = stability_ids(page_key)
    title = page_key.replace("_", " ").title()

    # Determine pedagogic content
    pedagogic_content = html.Div(["à compléter"])
    if layout_pedagogic_fn is not None:
        pedagogic_content = layout_pedagogic_fn()

    return html.Div(
        [
            # Back link to Poincaré
            html.Div(
                [
                    html.A(
                        "← Retour au diagramme de Poincaré",
                        href="/poincare",
                        style=back_link(),
                    )
                ],
                style={"marginBottom": "16px"},
            ),
            # Title
            html.H2(title, style=TEXT["h2"]),
            # Section: Paramètres du système
            html.Div(
                [
                    html.H3("Paramètres du système", style=TEXT["h3"]),
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.Strong(
                                        "Trace (τ) : ", style={"color": PALETTE.text}
                                    ),
                                    html.Span(
                                        f"τ = {tau:.2f}",
                                        style={
                                            "color": PALETTE.primary,
                                            "fontWeight": "bold",
                                        },
                                    ),
                                ],
                                style={"marginBottom": "0.5rem"},
                            ),
                            html.Div(
                                [
                                    html.Strong(
                                        "Déterminant (Δ) : ",
                                        style={"color": PALETTE.text},
                                    ),
                                    html.Span(
                                        f"Δ = {delta:.2f}",
                                        style={
                                            "color": PALETTE.primary,
                                            "fontWeight": "bold",
                                        },
                                    ),
                                ],
                                style={"marginBottom": "0.5rem"},
                            ),
                            html.Div(
                                [
                                    html.Strong(
                                        "Équation différentielle : ",
                                        style={"color": PALETTE.text},
                                    ),
                                ],
                                style={"marginBottom": "0.5rem"},
                            ),
                            html.Div(
                                id=ids["ode_display"],
                                style={
                                    **code_display(),
                                    "marginTop": "0.5rem",
                                    "marginBottom": "1rem",
                                },
                            ),
                            html.Div(
                                id=ids["eigenvalue_display"],
                                style={
                                    **code_display(),
                                    "marginTop": "1rem",
                                },
                            ),
                        ],
                    ),
                ],
                style={**section_card(), "marginBottom": "20px"},
            ),
            # Section: Graphes côte à côte
            html.Div(
                [
                    # Graphe temporel
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.H3("Évolution temporelle", style=TEXT["h3"]),
                                    html.Div(
                                        [
                                            dcc.Graph(id=ids["system_graph"]),
                                        ],
                                        style=graph_container(),
                                    ),
                                ],
                                style=section_card(),
                            ),
                        ],
                        style=side_by_side_container(),
                    ),
                    # Diagramme de phase
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.H3("Diagramme de phase", style=TEXT["h3"]),
                                    html.Div(
                                        [
                                            dcc.Graph(id=ids["phase"]),
                                        ],
                                        style=graph_container(),
                                    ),
                                ],
                                style=section_card(),
                            ),
                        ],
                        style=side_by_side_last(),
                    ),
                ],
                style=spacing_section("top"),
            ),
            # Section: Explication pédagogique
            html.Div(
                [
                    html.H3("Explication pédagogique", style=TEXT["h3"]),
                    html.Div(pedagogic_content, id=ids["explication"], style=TEXT["p"]),
                ],
                style=section_card(),
            ),
            # Section: Navigation
            html.Div(
                [
                    html.Div(
                        [
                            html.A(
                                "→ Accéder au diagramme de Poincaré",
                                href="/poincare",
                                style=nav_button("primary"),
                            ),
                            html.A(
                                "→ Voir le sommaire de stabilité",
                                href="/stabilite",
                                style=nav_button("secondary"),
                            ),
                        ],
                        style=spacing_section("top"),
                    ),
                ],
                style=section_card(),
            ),
        ],
        style={
            **app_container(),
            **content_wrapper(),
        },
    )
