"""
Base layout template for all stability analysis pages.

Each equilibrium type (foyer, nœud, selle, etc.) uses this template to display:
1. Back link to Poincaré diagram
2. Title and pedagogical explanation
3. Eigenvalue display
4. System ODE equation
5. Phase portrait diagram
6. Navigation to related pages

The layout is generated by build_stability_layout() which accepts a page_key
to generate unique element IDs for Dash callbacks.
"""

from __future__ import annotations

from typing import Dict, Optional, Callable

from dash import Input, Output, callback, dcc, html
import plotly.graph_objects as go

from src.app.style.components.layout import (
    code_display,
    content_wrapper,
    graph_container,
    section_card,
    side_by_side_container,
    side_by_side_last,
    spacing_section,
)
from src.app.style.palette import PALETTE
from src.app.style.text import TEXT
from src.app.style.typography import TYPOGRAPHY


def _slugify(page_key: str) -> str:
    """
    Very small slugifier: lowercase + replace spaces/underscores with hyphens
    and strip leading/trailing hyphens. Meant to keep IDs simple and stable.
    """
    slug = (page_key or "page").lower().replace("_", "-").replace(" ", "-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-") or "page"


def stability_ids(page_key: str) -> Dict[str, str]:
    """
    Provide normalized IDs for the standard placeholders on a stability page.
    """
    slug = _slugify(page_key)
    return {
        "graph": f"ph-{slug}-graph",
        "system_graph": f"ph-{slug}-system-graph",
        "phase": f"ph-{slug}-phase",
        "explication": f"ph-{slug}-explication",
        "eigenvalue_display": f"ph-{slug}-eigenvalue-display",
        "ode_display": f"ph-{slug}-ode-display",
    }


def build_stability_layout(
    page_key: str,
    layout_pedagogic_fn=None,
    tau: float = 0.0,
    delta: float = 0.0,
    create_phase_fig: Optional[Callable[[], go.Figure]] = None,
) -> html.Div:
    """
    Create a static stability layout with pre-rendered figures (no callbacks).
    
    This function generates all content (eigenvalues, ODEs, figures) directly
    without relying on Dash callbacks, making it suitable for both standalone
    pages and inline display.

    Args:
        page_key: Unique identifier for the page
        layout_pedagogic_fn: Function returning pedagogical content
        tau: Trace value for this equilibrium type
        delta: Determinant value for this equilibrium type
        create_phase_fig: Optional function that returns the phase diagram figure
    """
    # Import here to avoid circular dependencies
    from .base_figures import create_phase_diagram, create_system_graph
    from .eigenvalue_utils import (
        tau_delta_to_matrix_typed,
        format_eigenvalue_display,
        classify_equilibrium,
    )
    
    title = page_key.replace("_", " ").title()
    
    # Determine pedagogic content
    pedagogic_content = html.Div(["à compléter"])
    if layout_pedagogic_fn is not None:
        pedagogic_content = layout_pedagogic_fn()
    
    # Generate eigenvalue display
    eigenvalue_info = format_eigenvalue_display(tau, delta)
    eigenvalue_display = html.Div([
        html.Div(
            [
                html.Strong(
                    "Type de point d'équilibre : ", style={"color": PALETTE.primary}
                ),
                html.Span(eigenvalue_info["type"]),
            ],
            style={"marginBottom": "1rem"},
        ),
        html.Div(
            [
                html.Strong("Valeurs propres : "),
                html.Span(eigenvalue_info["eigenvalues"]),
            ],
            style={"marginBottom": "0.5rem"},
        ),
        html.Div(
            [
                html.Strong("Nature : "),
                html.Span(eigenvalue_info["nature"]),
            ]
        ),
    ])
    
    # Generate ODE display
    a, b, c, d = tau_delta_to_matrix_typed(tau, delta, page_key)
    
    def format_coeff(val: float) -> str:
        if val == 0:
            return "0"
        elif val == 1:
            return ""
        elif val == -1:
            return "-"
        else:
            return f"{val:.2f}" if val != int(val) else str(int(val))
    
    x1_terms = []
    if b != 0:
        if b > 0:
            x1_terms.append(f"+ {format_coeff(b)}x₂" if format_coeff(b) else "+ x₂")
        else:
            x1_terms.append(f"- {format_coeff(-b)}x₂" if format_coeff(-b) else "- x₂")
    if a > 0:
        x1_terms.insert(0, f"{format_coeff(a)}x₁" if format_coeff(a) else "x₁")
    elif a < 0:
        x1_terms.insert(0, f"- {format_coeff(-a)}x₁" if format_coeff(-a) else "- x₁")
    
    x2_terms = []
    if c != 0:
        if c > 0:
            x2_terms.append(f"+ {format_coeff(c)}x₁" if format_coeff(c) else "+ x₁")
        else:
            x2_terms.append(f"- {format_coeff(-c)}x₁" if format_coeff(-c) else "- x₁")
    if d > 0:
        x2_terms.insert(0, f"{format_coeff(d)}x₂" if format_coeff(d) else "x₂")
    elif d < 0:
        x2_terms.insert(0, f"- {format_coeff(-d)}x₂" if format_coeff(-d) else "- x₂")
    
    x1_eq = " ".join(x1_terms) if x1_terms else "0"
    x2_eq = " ".join(x2_terms) if x2_terms else "0"
    
    x1_eq = x1_eq.strip().lstrip("+ ").replace("  ", " ")
    x2_eq = x2_eq.strip().lstrip("+ ").replace("  ", " ")
    
    ode_display = html.Div(
        children=f"""
        $$\\dot{{x}}_1 = {x1_eq}$$
        $$\\dot{{x}}_2 = {x2_eq}$$
        """
    )
    
    # Generate phase diagram
    if create_phase_fig is not None:
        phase_fig = create_phase_fig()
    else:
        eq_type = classify_equilibrium(tau, delta)
        phase_fig = create_phase_diagram(a, b, c, d, title=f"Diagramme de phase: {eq_type}")
    
    # Generate system graph
    eq_type = classify_equilibrium(tau, delta)
    system_fig = create_system_graph(a, b, c, d, title=f"Évolution temporelle: {eq_type}")

    return html.Div(
        [
            # Title
            html.H2(title, style=TEXT["h2"]),
            # Section: Paramètres du système
            html.Div(
                [
                    html.H3("Paramètres du système", style=TEXT["h3"]),
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.Strong(
                                        "Trace (τ) : ", style={"color": PALETTE.text}
                                    ),
                                    html.Span(
                                        f"τ = {tau:.2f}",
                                        style={
                                            "color": PALETTE.primary,
                                            "fontWeight": "bold",
                                        },
                                    ),
                                ],
                                style={"marginBottom": "0.5rem"},
                            ),
                            html.Div(
                                [
                                    html.Strong(
                                        "Déterminant (Δ) : ",
                                        style={"color": PALETTE.text},
                                    ),
                                    html.Span(
                                        f"Δ = {delta:.2f}",
                                        style={
                                            "color": PALETTE.primary,
                                            "fontWeight": "bold",
                                        },
                                    ),
                                ],
                                style={"marginBottom": "0.5rem"},
                            ),
                            html.Div(
                                [
                                    html.Strong(
                                        "Équation différentielle : ",
                                        style={"color": PALETTE.text},
                                    ),
                                ],
                                style={"marginBottom": "0.5rem"},
                            ),
                            html.Div(
                                ode_display,
                                style={
                                    **code_display(),
                                    "marginTop": "0.5rem",
                                    "marginBottom": "1rem",
                                },
                            ),
                            html.Div(
                                eigenvalue_display,
                                style={
                                    **code_display(),
                                    "marginTop": "1rem",
                                },
                            ),
                        ],
                    ),
                ],
                style={**section_card(), "marginBottom": "20px"},
            ),
            # Section: Graphes côte à côte
            html.Div(
                [
                    # Graphe temporel
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.H3("Évolution temporelle", style=TEXT["h3"]),
                                    html.Div(
                                        [
                                            dcc.Graph(figure=system_fig, config={"displayModeBar": False}),
                                        ],
                                        style=graph_container(),
                                    ),
                                ],
                                style=section_card(),
                            ),
                        ],
                        style=side_by_side_container(),
                    ),
                    # Diagramme de phase
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.H3("Diagramme de phase", style=TEXT["h3"]),
                                    html.Div(
                                        [
                                            dcc.Graph(figure=phase_fig, config={"displayModeBar": False}),
                                        ],
                                        style=graph_container(),
                                    ),
                                ],
                                style=section_card(),
                            ),
                        ],
                        style=side_by_side_last(),
                    ),
                ],
                style=spacing_section("top"),
            ),
            # Section: Explication pédagogique
            html.Div(
                [
                    html.H3("Explication pédagogique", style=TEXT["h3"]),
                    html.Div(pedagogic_content, style=TEXT["p"]),
                ],
                style=section_card(),
            ),
        ],
        style=content_wrapper(margin_left_px=0),
    )
